### ISSUE TITLE
An option not to ever hide my buffers ?

### ISSUE THREAD

**Issue by Wyvern67** [glowing-bear/glowing-bear#869]
I have a vertical screen and this feature is starting to get on my nerves.

**Comment by Vaesper** [comment]
Sounds like you are on the mobile layout (gets triggered if the window width is 968px or smaller). If so, you did not miss a checkbox, it's true that there isn't one.

**Comment by lorenzhs** [comment]
Yeah you're getting the mobile layout. Best workaround is too keep the window at over 968px, but the real fix would be to improve detection of mobile devices. That's sort of a known issue.

**Comment by Vaesper** [comment]
Custom CSS workaround:

```CSS
#sidebar[data-state=hidden] {
    transform: translate(0,0);
    -webkit-transform: translate(0,0);
}

.content[sidebar-state=hidden] #bufferlines, .content[sidebar-state=hidden] .footer {
    margin-left: 200px;
}
```
