### ISSUE TITLE
Some plugins can be too wide

### ISSUE THREAD

**Issue by lorenzhs** [glowing-bear/glowing-bear#957]
Github's gists are a frequent offender. We should look into whether we can limit their width to whatever space there is in the buffer area, otherwise it'll break wrapping.

Reported by yegortimoshenko on IRC, thanks!

**Comment by lorenzhs** [comment]
```css
.gist {
   max-width: 500px;
   overflow:auto;
}

.gist .blob-wrapper.data {
   max-height: 500px;
   overflow:auto;
}
```
